# please see https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/ for this yml setting.

service: try-serverless

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: ap-northeast-1
  environment:
    slackChannel: ${env:SLACK_CHANNEL}
    hookUrl: ${env:HOOK_URL}

functions:
  notify_slack:
    handler: handler.notify_slack
    name: notify_slack-${self:provider.stage}
    description: "log message post to slack."
    memorySize: 128
    runtime: python2.7
    timeout: 3
    role: arn:aws:iam::059991434768:role/lambda-role
